//! OpenWrt-only backend for native Apply.
//!
//! The production confirmation command and private laboratory gates share this
//! backend. It uses fixed executable paths and argv, one bounded UCI batch on
//! stdin, the exact inherited runtime lock during service restart, and strict
//! post-restart verification around the durable transaction boundary.

use super::autotune_apply::{
    NativeApplyAction, NativeApplyExecutionPlan, NativeUciMutation, NativeUciMutationAction,
};
use super::autotune_apply_runtime::{
    read_config_snapshot, NativeApplyGlobalLock, NativeApplyRecoveryRecord,
    NativeApplyTransactionBackend, NativeApplyTransactionPaths,
};
use super::autotune_bootstrap_apply::{NativeBootstrapApplyMode, NativeBootstrapApplyPlan};
use super::autotune_bootstrap_apply_recovery::{
    NativeBootstrapApplyRecoveryRecord, NativeBootstrapApplyRecoveryState,
};
use super::autotune_bootstrap_apply_runtime::{
    absent_baseline_from_record, NativeBootstrapApplyBackend,
};
use super::autotune_runtime::AbsentRuntimeBaseline;
use super::autotune_uci_materialization::NativeUciMaterializationPlan;
use super::kernel_topology::{
    capture_read_only_witness, ExpectedOwnedTopology, KernelTopologyStagePolicy,
};
use super::kernel_topology_netlink::{LinuxNetlinkIo, NetlinkTopologyReader};
use super::native_apply_lifecycle::{
    run_selected_instance_lifecycle, SelectedLifecycleAction as NativeApplyInstanceAction,
};
use super::process::{run_bounded_command_output_with_input, SpawnSpec};
use super::protocol::{OperationRequest, OperationRouteMode, OperationTargetState};
use super::runtime::{attest_openwrt_route_identity, attest_openwrt_runtime, RuntimeAttestation};
use super::sqm_identity::{attest_bootstrap_uci_absence, BootstrapAbsenceIdentity};
use crate::{root_cake_qdisc, root_cake_qdisc_count, tc_output, Config};
use std::ffi::OsString;
use std::fs::{self, DirBuilder};
use std::io::{ErrorKind, Read};
use std::os::unix::fs::{DirBuilderExt, MetadataExt};
use std::path::{Path, PathBuf};
use std::thread;
use std::time::{Duration, Instant};

const UCI_PROGRAM: &str = "/sbin/uci";
const PRIVATE_UCI_SAVEDIR: &str = "/tmp/cake-autorate-native-apply-uci";
const CAKE_CONFIG_PATH: &str = "/etc/config/cake-autorate";
const SQM_CONFIG_PATH: &str = "/etc/config/sqm";
const APPLY_COMMAND_TIMEOUT: Duration = Duration::from_secs(15);
const VERIFY_TIMEOUT: Duration = Duration::from_secs(30);
const VERIFY_INTERVAL: Duration = Duration::from_millis(200);
const COMMAND_OUTPUT_LIMIT: usize = 16 * 1024;
const PROC_CMDLINE_LIMIT: u64 = 4 * 1024;

pub(crate) fn default_native_apply_paths() -> NativeApplyTransactionPaths<'static> {
    NativeApplyTransactionPaths {
        recovery_root: Path::new("/etc/cake-autorate-rs/native-apply-recovery"),
        global_lock: Path::new("/tmp/cake-autorate-speedtest/runtime.guard"),
        cake_config: Path::new("/etc/config/cake-autorate"),
        sqm_config: Path::new("/etc/config/sqm"),
    }
}

pub(crate) struct OpenWrtNativeApplyBackend;

impl OpenWrtNativeApplyBackend {
    /// Capture the initial positive absence witness for a coordinator-owned
    /// bootstrap runtime permit.  The supplied namespace seed is generated by
    /// the coordinator and later becomes the permit ID; no rate, qdisc or
    /// throughput evidence is inferred here.
    pub(crate) fn capture_bootstrap_runtime_baseline(
        &self,
        request: &OperationRequest,
        kernel_namespace_seed: &str,
    ) -> Result<AbsentRuntimeBaseline, String> {
        let provisional = AbsentRuntimeBaseline {
            planned_sqm_section: request.managed_sqm_section.clone().ok_or_else(|| {
                "bootstrap runtime request has no planned SQM section".to_string()
            })?,
            target_interface: request.identity.target_interface.clone(),
            target_ifindex: 1,
            route_fingerprint: request.identity.route_fingerprint.clone(),
            config_fingerprint: request.identity.config_fingerprint.clone(),
            sqm_fingerprint: request.identity.sqm_fingerprint.clone(),
            // The provisional digest is only a structurally valid query
            // carrier and is replaced by the observed canonical digest before
            // this method returns.
            kernel_topology_fingerprint: "0".repeat(64),
            kernel_namespace_seed: kernel_namespace_seed.to_string(),
        };
        provisional.validate()?;
        self.require_bootstrap_root()?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "runtime baseline preflight")?;
        let first_uci = self.attest_bootstrap_uci_absence_once(request, &provisional)?;
        self.require_bootstrap_managed_slots_absent(request)?;

        let query = provisional.kernel_topology_query(request.route.clone())?;
        let io = LinuxNetlinkIo::open()
            .map_err(|error| format!("bootstrap runtime netlink open failed: {error}"))?;
        let mut reader = NetlinkTopologyReader::new(io);
        let witness = capture_read_only_witness(&mut reader, &query)
            .map_err(|error| format!("bootstrap runtime topology read failed: {error}"))?;
        witness
            .snapshot()
            .validate_stage_policy(&KernelTopologyStagePolicy::BarePreflight(
                ExpectedOwnedTopology::default(),
            ))
            .map_err(|error| format!("bootstrap runtime bare topology check failed: {error}"))?;

        attest_bootstrap_route(request, "runtime baseline re-attestation")?;
        let second_uci = self.attest_bootstrap_uci_absence_once(request, &provisional)?;
        first_uci.ensure_exact_reattestation(&second_uci)?;
        self.require_bootstrap_managed_slots_absent(request)?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "runtime baseline final route fence")?;

        let baseline = AbsentRuntimeBaseline {
            target_ifindex: witness.snapshot().target.ifindex,
            kernel_topology_fingerprint: witness.digest().to_hex(),
            ..provisional
        };
        baseline.validate()?;
        validate_bootstrap_request_baseline(request, &baseline)?;
        Ok(baseline)
    }

    /// Re-attest the complete positive absence witness for the job-scoped
    /// bootstrap runtime owner.  Keeping this in the Apply backend avoids a
    /// second, subtly different UCI/route/netlink authority implementation.
    pub(crate) fn attest_bootstrap_runtime_absence(
        &self,
        request: &OperationRequest,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<(), String> {
        self.attest_bootstrap_absence(request, baseline)
    }

    /// Re-attest only the immutable UCI and route identity while the exact
    /// calibration-private topology is expected to be present.  Kernel
    /// ownership is checked separately against the durable checkpoint before
    /// any destructive operation.
    pub(crate) fn attest_bootstrap_runtime_identity(
        &self,
        request: &OperationRequest,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<(), String> {
        self.require_bootstrap_root()?;
        self.require_clean_uci()?;
        validate_bootstrap_request_baseline(request, baseline)?;
        attest_bootstrap_route(request, "runtime identity preflight")?;
        let first = self.attest_bootstrap_uci_absence_once(request, baseline)?;
        attest_bootstrap_route(request, "runtime identity re-attestation")?;
        let second = self.attest_bootstrap_uci_absence_once(request, baseline)?;
        first.ensure_exact_reattestation(&second)?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "runtime identity final route fence")
    }

    pub(crate) fn new() -> Self {
        Self
    }

    fn ensure_private_uci_savedir(&self) -> Result<(), String> {
        let path = Path::new(PRIVATE_UCI_SAVEDIR);
        match fs::symlink_metadata(path) {
            Ok(metadata) => {
                if !metadata.file_type().is_dir()
                    || metadata.uid() != unsafe { libc::geteuid() }
                    || metadata.mode() & 0o077 != 0
                {
                    return Err(
                        "native Apply private UCI savedir is not a private owner directory"
                            .to_string(),
                    );
                }
            }
            Err(error) if error.kind() == ErrorKind::NotFound => {
                let mut builder = DirBuilder::new();
                builder.mode(0o700);
                match builder.create(path) {
                    Ok(()) => {}
                    Err(create_error) if create_error.kind() == ErrorKind::AlreadyExists => {
                        return self.ensure_private_uci_savedir();
                    }
                    Err(create_error) => {
                        return Err(format!(
                            "unable to create native Apply private UCI savedir: {create_error}"
                        ));
                    }
                }
            }
            Err(error) => {
                return Err(format!(
                    "unable to inspect native Apply private UCI savedir: {error}"
                ));
            }
        }
        Ok(())
    }

    fn private_uci_arguments(arguments: &[&str]) -> Vec<OsString> {
        let mut private = Vec::with_capacity(arguments.len() + 2);
        private.push(OsString::from("-t"));
        private.push(OsString::from(PRIVATE_UCI_SAVEDIR));
        private.extend(arguments.iter().map(OsString::from));
        private
    }

    fn run_private_uci(
        &self,
        arguments: &[&str],
        input: Option<&[u8]>,
    ) -> Result<super::process::BoundedCommandOutput, String> {
        self.ensure_private_uci_savedir()?;
        let spec = SpawnSpec {
            program: PathBuf::from(UCI_PROGRAM),
            arguments: Self::private_uci_arguments(arguments),
            environment: Vec::new(),
        };
        run_bounded_command_output_with_input(
            &spec,
            input,
            APPLY_COMMAND_TIMEOUT,
            COMMAND_OUTPUT_LIMIT,
            || false,
            |_| {},
        )
        .map_err(|error| format!("native Apply private UCI command failed: {error}"))
    }

    fn require_private_uci_clean(&self) -> Result<(), String> {
        self.ensure_private_uci_savedir()?;
        for package in ["cake-autorate", "sqm"] {
            let output = self.run_private_uci(&["-q", "changes", package], None)?;
            if !output.status.success() {
                return Err(format!(
                    "native Apply could not inspect its private UCI changes for {package}: {}",
                    bounded_stderr(&output.stderr)
                ));
            }
            if !output.stdout.is_empty() {
                return Err(format!(
                    "native Apply private UCI transaction is not clean: {package}"
                ));
            }
        }
        let entries = fs::read_dir(PRIVATE_UCI_SAVEDIR).map_err(|error| {
            format!("unable to inspect native Apply private UCI files: {error}")
        })?;
        for entry in entries {
            let entry = entry.map_err(|error| {
                format!("unable to inspect a native Apply private UCI entry: {error}")
            })?;
            let name = entry.file_name();
            if name != "cake-autorate" && name != "sqm" {
                return Err(
                    "native Apply private UCI savedir contains an unknown entry".to_string()
                );
            }
            let metadata = fs::symlink_metadata(entry.path()).map_err(|error| {
                format!("unable to inspect a native Apply private UCI file: {error}")
            })?;
            if !metadata.file_type().is_file()
                || metadata.uid() != unsafe { libc::geteuid() }
                || metadata.mode() & 0o077 != 0
                || metadata.len() != 0
            {
                return Err("native Apply private UCI savedir contains unsafe residue".to_string());
            }
        }
        Ok(())
    }

    fn run_uci(
        &self,
        arguments: &[&str],
        input: Option<&[u8]>,
    ) -> Result<super::process::BoundedCommandOutput, String> {
        let spec = SpawnSpec {
            program: PathBuf::from(UCI_PROGRAM),
            arguments: arguments.iter().map(OsString::from).collect(),
            environment: Vec::new(),
        };
        run_bounded_command_output_with_input(
            &spec,
            input,
            APPLY_COMMAND_TIMEOUT,
            COMMAND_OUTPUT_LIMIT,
            || false,
            |_| {},
        )
        .map_err(|error| format!("native Apply UCI command failed: {error}"))
    }

    fn run_instance_service_action(
        &self,
        action: NativeApplyInstanceAction,
        request: &OperationRequest,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        self.run_instance_service_action_for_target(
            action,
            request,
            &request.identity.target_interface,
            lock,
        )
    }

    fn run_bootstrap_instance_service_action(
        &self,
        action: NativeApplyInstanceAction,
        request: &OperationRequest,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        self.run_instance_service_action_for_target(action, request, &request.route.l3_device, lock)
    }

    fn run_instance_service_action_for_target(
        &self,
        action: NativeApplyInstanceAction,
        request: &OperationRequest,
        managed_target_interface: &str,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        run_selected_instance_lifecycle(action, request, managed_target_interface, lock)
    }

    fn require_clean_uci(&self) -> Result<(), String> {
        for package in ["cake-autorate", "sqm"] {
            let output = self.run_uci(&["-q", "changes", package], None)?;
            if !output.status.success() {
                return Err(format!(
                    "native Apply could not inspect pending UCI changes for {package}: {}",
                    bounded_stderr(&output.stderr)
                ));
            }
            if !output.stdout.is_empty() {
                return Err(format!(
                    "native Apply requires a clean UCI package before mutation: {package}"
                ));
            }
        }
        self.require_private_uci_clean()
    }

    fn require_bootstrap_root(&self) -> Result<(), String> {
        if unsafe { libc::geteuid() } == 0 {
            Ok(())
        } else {
            Err("native bootstrap Apply execution requires root".to_string())
        }
    }

    fn read_bootstrap_config_pair(&self) -> Result<(Vec<u8>, Vec<u8>), String> {
        let (cake, _) = read_config_snapshot(
            Path::new(CAKE_CONFIG_PATH),
            "native bootstrap cake-autorate",
        )?;
        let (sqm, _) = read_config_snapshot(Path::new(SQM_CONFIG_PATH), "native bootstrap sqm")?;
        Ok((cake, sqm))
    }

    fn verify_bootstrap_materialized_config(
        &self,
        plan: &NativeBootstrapApplyPlan,
    ) -> Result<Config, String> {
        let _ = plan.canonical_manifest_bytes()?;
        let materialization =
            NativeUciMaterializationPlan::from_managed_config(plan.managed_config())?;
        materialization.ensure_bound_to(plan.managed_config())?;
        let (cake, sqm) = self.read_bootstrap_config_pair()?;
        materialization.verify_exact_config_files(&cake, &sqm)?;
        let cfg = self.verify_bootstrap_candidate_config(plan.request(), plan.mode())?;
        if cfg.sqm_direction_mode != plan.source_apply().sqm_direction_mode.as_str() {
            return Err(
                "native bootstrap candidate direction mode differs from the selected plan"
                    .to_string(),
            );
        }
        Ok(cfg)
    }

    fn attest_bootstrap_uci_absence_once(
        &self,
        request: &OperationRequest,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<BootstrapAbsenceIdentity, String> {
        validate_bootstrap_request_baseline(request, baseline)?;
        let section = request.managed_sqm_section.as_deref().ok_or_else(|| {
            "native bootstrap Apply request has no planned SQM section".to_string()
        })?;
        let witness = attest_bootstrap_uci_absence(
            &request.identity.instance,
            section,
            &request.identity.target_interface,
            &request.identity.route_fingerprint,
        )?;
        witness.ensure_request_binding(
            &request.identity.instance,
            section,
            &request.identity.target_interface,
            &request.identity.route_fingerprint,
            &baseline.config_fingerprint,
            &baseline.sqm_fingerprint,
        )?;
        Ok(witness)
    }

    fn attest_bootstrap_kernel_bare(
        &self,
        request: &OperationRequest,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<(), String> {
        validate_bootstrap_request_baseline(request, baseline)?;
        let query = baseline.kernel_topology_query(request.route.clone())?;
        let io = LinuxNetlinkIo::open()
            .map_err(|error| format!("native bootstrap netlink open failed: {error}"))?;
        let mut reader = NetlinkTopologyReader::new(io);
        let witness = capture_read_only_witness(&mut reader, &query)
            .map_err(|error| format!("native bootstrap topology read failed: {error}"))?;
        if witness.snapshot().target.ifindex != baseline.target_ifindex {
            return Err("native bootstrap target ifindex changed".to_string());
        }
        if witness.digest().to_hex() != baseline.kernel_topology_fingerprint {
            return Err("native bootstrap kernel topology fingerprint changed".to_string());
        }
        witness
            .snapshot()
            .validate_stage_policy(&KernelTopologyStagePolicy::BarePreflight(
                ExpectedOwnedTopology::default(),
            ))
            .map_err(|error| format!("native bootstrap bare topology check failed: {error}"))
    }

    fn require_bootstrap_managed_slots_absent(
        &self,
        request: &OperationRequest,
    ) -> Result<(), String> {
        let managed_ifb = format!("ifb4{}", request.route.l3_device);
        validate_init_interface(&managed_ifb)?;
        if Path::new("/sys/class/net").join(&managed_ifb).exists() {
            return Err(format!(
                "native bootstrap managed download interface {managed_ifb} already exists"
            ));
        }
        let qdiscs = tc_output(&["qdisc", "show", "dev", &request.route.l3_device])?;
        let ingress = tc_output(&["filter", "show", "dev", &request.route.l3_device, "ingress"])?;
        validate_bootstrap_managed_slot_output(&request.route.l3_device, &qdiscs, &ingress)
    }

    fn attest_bootstrap_absence(
        &self,
        request: &OperationRequest,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<(), String> {
        self.require_bootstrap_root()?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "absence preflight")?;
        let first_uci = self.attest_bootstrap_uci_absence_once(request, baseline)?;
        self.require_bootstrap_managed_slots_absent(request)?;
        self.attest_bootstrap_kernel_bare(request, baseline)?;
        attest_bootstrap_route(request, "absence re-attestation")?;
        let second_uci = self.attest_bootstrap_uci_absence_once(request, baseline)?;
        first_uci.ensure_exact_reattestation(&second_uci)?;
        self.require_bootstrap_managed_slots_absent(request)?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "absence final route fence")
    }

    fn verify_bootstrap_candidate_config(
        &self,
        request: &OperationRequest,
        mode: NativeBootstrapApplyMode,
    ) -> Result<Config, String> {
        let cfg = Config::from_uci(&request.identity.instance)?;
        validate_bootstrap_candidate_config(&cfg, request, mode)?;
        self.verify_bootstrap_managed_sqm_owner(request, &cfg, mode)?;
        Ok(cfg)
    }

    fn verify_bootstrap_managed_sqm_owner(
        &self,
        request: &OperationRequest,
        cfg: &Config,
        mode: NativeBootstrapApplyMode,
    ) -> Result<(), String> {
        let section = request.managed_sqm_section.as_deref().ok_or_else(|| {
            "native bootstrap Apply request has no planned SQM section".to_string()
        })?;
        if mode == NativeBootstrapApplyMode::DisabledInactive {
            return self.verify_bootstrap_sqm_section_absent(section);
        }
        for (option, expected) in [
            ("_cake_autorate_managed", request.identity.instance.as_str()),
            ("interface", request.route.l3_device.as_str()),
            ("enabled", if cfg.sqm_enabled { "1" } else { "0" }),
        ] {
            let query = format!("sqm.{section}.{option}");
            let output = self.run_uci(&["-q", "get", &query], None)?;
            if !output.status.success() || parse_uci_scalar_output(&output.stdout)? != expected {
                return Err(format!(
                    "native bootstrap managed SQM option {query} violates its owner contract"
                ));
            }
        }
        Ok(())
    }

    fn verify_bootstrap_sqm_section_absent(&self, section: &str) -> Result<(), String> {
        validate_init_identifier(section)?;
        let query = format!("sqm.{section}");
        let output = self.run_uci(&["-q", "show", &query], None)?;
        if output.status.code() == Some(1) && output.stdout.is_empty() && output.stderr.is_empty() {
            return Ok(());
        }
        Err(format!(
            "native disabled bootstrap candidate unexpectedly owns SQM section {query}"
        ))
    }

    fn verify_bootstrap_running_candidate(
        &self,
        request: &OperationRequest,
        expected_direction_mode: Option<&str>,
        mode: NativeBootstrapApplyMode,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<(), String> {
        self.require_bootstrap_root()?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "running candidate preflight")?;
        let cfg = self.verify_bootstrap_candidate_config(request, mode)?;
        if let Some(expected) = expected_direction_mode {
            if cfg.sqm_direction_mode != expected {
                return Err(
                    "native bootstrap running direction mode differs from the selected plan"
                        .to_string(),
                );
            }
        }
        if mode == NativeBootstrapApplyMode::DisabledInactive {
            require_selected_controller_absent(Path::new("/proc"), &request.identity.instance)?;
            self.require_bootstrap_managed_slots_absent(request)?;
            self.attest_bootstrap_kernel_bare(request, baseline)?;
            self.require_clean_uci()?;
            return attest_bootstrap_route(request, "disabled candidate final route fence");
        }
        let expected_download = if cfg.download_shaping_enabled() {
            Some(exact_config_rate("download", cfg.base_dl_shaper_rate_kbps)?)
        } else {
            None
        };
        let expected_upload = if cfg.upload_shaping_enabled() {
            Some(exact_config_rate("upload", cfg.base_ul_shaper_rate_kbps)?)
        } else {
            None
        };
        verify_direction_rate("download", &cfg.dl_if, expected_download)?;
        verify_direction_rate("upload", &cfg.ul_if, expected_upload)?;
        if cfg.dl_if.starts_with("ifb") {
            let ingress = tc_output(&["filter", "show", "dev", &cfg.sqm_interface, "ingress"])?;
            if expected_download.is_some() {
                crate::attest_exclusive_sqm_ingress(&ingress, &cfg.sqm_interface, &cfg.dl_if)
                    .map_err(|error| error.to_string())?;
            } else {
                crate::attest_download_redirect(&ingress, false, &cfg.sqm_interface, &cfg.dl_if)
                    .map_err(|error| error.to_string())?;
            }
        }
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "running candidate final route fence")
    }

    fn quiesce_bootstrap_candidate(
        &self,
        request: &OperationRequest,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        self.require_bootstrap_root()?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "rollback quiesce preflight")?;
        let cfg = self
            .verify_bootstrap_candidate_config(request, NativeBootstrapApplyMode::ShapedRuntime)?;
        self.run_bootstrap_instance_service_action(NativeApplyInstanceAction::Stop, request, lock)?;
        verify_direction_rate("download", &cfg.dl_if, None)?;
        verify_direction_rate("upload", &cfg.ul_if, None)?;
        if cfg.dl_if.starts_with("ifb") {
            let ingress = tc_output(&["filter", "show", "dev", &cfg.sqm_interface, "ingress"])?;
            crate::attest_download_redirect(&ingress, false, &cfg.sqm_interface, &cfg.dl_if)
                .map_err(|error| error.to_string())?;
        }
        self.require_bootstrap_managed_slots_absent(request)?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "rollback quiesce final route fence")
    }

    fn verify_exact_uci_plan(&self, plan: &NativeApplyExecutionPlan) -> Result<(), String> {
        for mutation in &plan.uci_mutations {
            let query = exact_uci_query(mutation);
            let output = self.run_uci(&["-q", "get", &query], None)?;
            match (&mutation.action, mutation.value.as_deref()) {
                (NativeUciMutationAction::Set, Some(expected)) => {
                    if !output.status.success() {
                        return Err(format!(
                            "native Apply UCI option {query} is unavailable after commit: {}",
                            bounded_stderr(&output.stderr)
                        ));
                    }
                    let actual = parse_uci_scalar_output(&output.stdout)?;
                    if actual != expected {
                        return Err(format!(
                            "native Apply UCI option {query} differs from the typed plan"
                        ));
                    }
                }
                (NativeUciMutationAction::Delete, None) => {
                    if output.status.success() || !output.stdout.is_empty() {
                        return Err(format!(
                            "native Apply UCI option {query} remains after an exact delete"
                        ));
                    }
                }
                _ => {
                    return Err(
                        "native Apply UCI action/value pair changed after planning".to_string()
                    )
                }
            }
        }
        Ok(())
    }

    fn verify_managed_sqm_section(&self, plan: &NativeApplyExecutionPlan) -> Result<(), String> {
        let section = plan
            .request
            .managed_sqm_section
            .as_deref()
            .ok_or_else(|| "native Apply plan has no managed SQM section".to_string())?;
        for (option, expected) in [
            (
                "_cake_autorate_managed",
                plan.request.identity.instance.as_str(),
            ),
            ("interface", plan.request.identity.target_interface.as_str()),
            (
                "enabled",
                if plan.action == NativeApplyAction::DisableSqm {
                    "0"
                } else {
                    "1"
                },
            ),
        ] {
            let query = format!("sqm.{section}.{option}");
            let output = self.run_uci(&["-q", "get", &query], None)?;
            if !output.status.success() || parse_uci_scalar_output(&output.stdout)? != expected {
                return Err(format!(
                    "native Apply generated SQM option {query} does not match its owner contract"
                ));
            }
        }
        Ok(())
    }

    fn verify_candidate_once(&self, plan: &NativeApplyExecutionPlan) -> Result<(), String> {
        self.require_clean_uci()?;
        self.verify_exact_uci_plan(plan)?;
        self.verify_managed_sqm_section(plan)?;
        attest_openwrt_route_identity(&plan.request).map_err(|(code, message, _)| {
            format!("native Apply route check failed ({code}): {message}")
        })?;

        let cfg = Config::from_uci(&plan.request.identity.instance)?;
        let expected_section = plan
            .request
            .managed_sqm_section
            .as_deref()
            .ok_or_else(|| "native Apply plan has no managed SQM section".to_string())?;
        if cfg.sqm_interface != plan.request.identity.target_interface
            || cfg.sqm_section != expected_section
            || cfg.sqm_direction_mode != plan.sqm_direction_mode.as_str()
        {
            return Err(
                "native Apply live instance topology differs from its typed plan".to_string(),
            );
        }

        let expected_download = plan.download.base_kbps;
        let expected_upload = plan.upload.base_kbps;
        verify_direction_rate("download", &cfg.dl_if, expected_download)?;
        verify_direction_rate("upload", &cfg.ul_if, expected_upload)?;

        if cfg.dl_if.starts_with("ifb") {
            let ingress = tc_output(&["filter", "show", "dev", &cfg.sqm_interface, "ingress"])?;
            crate::attest_download_redirect(
                &ingress,
                expected_download.is_some(),
                &cfg.sqm_interface,
                &cfg.dl_if,
            )
            .map_err(|error| error.to_string())?;
        }
        Ok(())
    }

    fn verify_candidate_bounded(&self, plan: &NativeApplyExecutionPlan) -> Result<(), String> {
        let deadline = Instant::now() + VERIFY_TIMEOUT;
        loop {
            match self.verify_candidate_once(plan) {
                Ok(()) => return Ok(()),
                Err(error) if Instant::now() >= deadline => {
                    return Err(format!(
                        "native Apply candidate did not settle before timeout: {error}"
                    ))
                }
                Err(_) => {}
            }
            thread::sleep(VERIFY_INTERVAL);
        }
    }

    fn verify_original_bounded(&self, request: &OperationRequest) -> Result<(), String> {
        let deadline = Instant::now() + VERIFY_TIMEOUT;
        loop {
            match attest_openwrt_runtime(request) {
                RuntimeAttestation::Ready => {
                    self.require_clean_uci()?;
                    return Ok(());
                }
                RuntimeAttestation::Waiting { code, message } => {
                    if Instant::now() >= deadline {
                        return Err(format!(
                            "restored native Apply runtime did not settle ({code}): {message}"
                        ));
                    }
                }
                RuntimeAttestation::Unsafe { code, message } => {
                    return Err(format!(
                        "restored native Apply runtime is unsafe ({code}): {message}"
                    ))
                }
            }
            thread::sleep(VERIFY_INTERVAL);
        }
    }
}

pub(crate) fn validate_bootstrap_request_baseline(
    request: &OperationRequest,
    baseline: &AbsentRuntimeBaseline,
) -> Result<(), String> {
    request.validate()?;
    baseline.validate()?;
    if request.target_state != OperationTargetState::AbsentBootstrap
        || request.managed_sqm_section.as_deref() != Some(baseline.planned_sqm_section.as_str())
        || request.identity.target_interface != baseline.target_interface
        || request.identity.route_fingerprint != baseline.route_fingerprint
        || request.identity.config_fingerprint != baseline.config_fingerprint
        || request.identity.sqm_fingerprint != baseline.sqm_fingerprint
    {
        return Err(
            "native bootstrap request does not match its absent runtime baseline".to_string(),
        );
    }
    Ok(())
}

fn attest_bootstrap_route(request: &OperationRequest, stage: &str) -> Result<(), String> {
    attest_openwrt_route_identity(request).map_err(|(code, message, _)| {
        format!("native bootstrap route {stage} failed ({code}): {message}")
    })
}

fn validate_bootstrap_candidate_config(
    cfg: &Config,
    request: &OperationRequest,
    mode: NativeBootstrapApplyMode,
) -> Result<(), String> {
    request.validate()?;
    if request.target_state != OperationTargetState::AbsentBootstrap {
        return Err(
            "native bootstrap candidate request is not absent-target authority".to_string(),
        );
    }
    let expected_section = request
        .managed_sqm_section
        .as_deref()
        .ok_or_else(|| "native bootstrap Apply request has no planned SQM section".to_string())?;
    let expected_member = request.route.mwan3_member.as_deref().unwrap_or("");
    let expected_dl_if = format!("ifb4{}", request.route.l3_device);
    if cfg.instance != request.identity.instance
        || !cfg.manage_sqm
        || cfg.sqm_section != expected_section
        || cfg.sqm_interface != request.route.l3_device
        || cfg.ul_if != request.route.l3_device
        || cfg.dl_if != expected_dl_if
        || cfg.route_mode != request.route.mode.as_str()
        || cfg.mwan3_member != expected_member
        || cfg.speedtest_backend != request.backend
    {
        return Err(
            "native bootstrap live candidate differs from its immutable request topology"
                .to_string(),
        );
    }
    let runtime_shape_valid = match mode {
        NativeBootstrapApplyMode::ShapedRuntime => {
            cfg.enabled
                && cfg.sqm_enabled
                && matches!(
                    cfg.sqm_direction_mode.as_str(),
                    "both" | "download_only" | "upload_only"
                )
                && (cfg.download_shaping_enabled() || cfg.upload_shaping_enabled())
        }
        NativeBootstrapApplyMode::DisabledInactive => {
            !cfg.enabled
                && !cfg.sqm_enabled
                && cfg.sqm_direction_mode == "off"
                && !cfg.download_shaping_enabled()
                && !cfg.upload_shaping_enabled()
        }
    };
    if !runtime_shape_valid {
        return Err(match mode {
            NativeBootstrapApplyMode::ShapedRuntime => {
                "native bootstrap shaped candidate has no authorized shaping runtime".to_string()
            }
            NativeBootstrapApplyMode::DisabledInactive => {
                "native bootstrap disabled candidate is not strictly inactive".to_string()
            }
        });
    }
    if request.route.mode == OperationRouteMode::Main && !cfg.mwan3_member.is_empty() {
        return Err("native bootstrap main-route candidate retained an mwan3 member".to_string());
    }
    Ok(())
}

fn require_selected_controller_absent(proc_root: &Path, instance: &str) -> Result<(), String> {
    validate_init_identifier(instance)?;
    let entries = fs::read_dir(proc_root)
        .map_err(|error| format!("unable to enumerate controller processes: {error}"))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("unable to inspect process entry: {error}"))?;
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        if name.is_empty() || !name.bytes().all(|byte| byte.is_ascii_digit()) {
            continue;
        }
        let path = entry.path().join("cmdline");
        let file = match fs::File::open(&path) {
            Ok(file) => file,
            Err(error) if error.kind() == ErrorKind::NotFound => continue,
            Err(error) => {
                return Err(format!(
                    "unable to read controller process {name} command line: {error}"
                ))
            }
        };
        let mut bytes = Vec::new();
        file.take(PROC_CMDLINE_LIMIT + 1)
            .read_to_end(&mut bytes)
            .map_err(|error| {
                format!("unable to read controller process {name} command line: {error}")
            })?;
        if bytes.len() > PROC_CMDLINE_LIMIT as usize {
            if selected_controller_cmdline_prefix(&bytes, instance) {
                return Err(format!(
                    "controller process {name} command line exceeds its safety bound"
                ));
            }
            continue;
        }
        if selected_controller_cmdline(&bytes, instance) {
            return Err(format!(
                "native disabled bootstrap candidate still has a live controller for {instance}"
            ));
        }
    }
    Ok(())
}

fn selected_controller_cmdline_prefix(bytes: &[u8], instance: &str) -> bool {
    let mut fields = bytes.split(|byte| *byte == 0);
    fields.next() == Some(b"/usr/sbin/cake-autorated".as_slice())
        && fields.next() == Some(b"--instance".as_slice())
        && fields.next() == Some(instance.as_bytes())
}

fn selected_controller_cmdline(bytes: &[u8], instance: &str) -> bool {
    let mut fields = bytes.split(|byte| *byte == 0);
    fields.next() == Some(b"/usr/sbin/cake-autorated".as_slice())
        && fields.next() == Some(b"--instance".as_slice())
        && fields.next() == Some(instance.as_bytes())
        && fields.next() == Some(b"".as_slice())
        && fields.next().is_none()
}

fn validate_bootstrap_managed_slot_output(
    interface: &str,
    qdisc_output: &str,
    ingress_filter_output: &str,
) -> Result<(), String> {
    if !ingress_filter_output.trim().is_empty() {
        return Err(format!(
            "native bootstrap target {interface} already has ingress filter ownership"
        ));
    }
    for line in qdisc_output
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
    {
        let fields = line.split_whitespace().collect::<Vec<_>>();
        if fields.first() != Some(&"qdisc") || fields.len() < 3 {
            return Err(format!(
                "native bootstrap target {interface} returned malformed qdisc state"
            ));
        }
        let kind = fields[1];
        let handle = fields[2];
        if fields.contains(&"root") {
            if handle != "0:" || !matches!(kind, "mq" | "noqueue" | "fq_codel" | "pfifo_fast") {
                return Err(format!(
                    "native bootstrap refuses to replace foreign root qdisc state on {interface}"
                ));
            }
        } else if matches!(kind, "ingress" | "clsact") {
            return Err(format!(
                "native bootstrap target {interface} already owns an ingress/clsact hook"
            ));
        }
    }
    Ok(())
}

impl NativeApplyTransactionBackend for OpenWrtNativeApplyBackend {
    fn candidate_already_applied(
        &mut self,
        plan: &NativeApplyExecutionPlan,
    ) -> Result<bool, String> {
        Ok(self.verify_candidate_once(plan).is_ok())
    }

    fn attest_before_apply(&mut self, plan: &NativeApplyExecutionPlan) -> Result<(), String> {
        if unsafe { libc::geteuid() } != 0 {
            return Err("native Apply execution requires root".to_string());
        }
        self.require_clean_uci()?;
        match attest_openwrt_runtime(&plan.request) {
            RuntimeAttestation::Ready => Ok(()),
            RuntimeAttestation::Waiting { code, message }
            | RuntimeAttestation::Unsafe { code, message } => Err(format!(
                "native Apply pre-attestation failed ({code}): {message}"
            )),
        }
    }

    fn apply_uci_batch(&mut self, batch: &[u8]) -> Result<(), String> {
        self.require_private_uci_clean()?;
        let output = self.run_private_uci(&["-q", "batch"], Some(batch))?;
        if !output.status.success() {
            return Err(format!(
                "native Apply UCI batch failed: {}",
                bounded_stderr(&output.stderr)
            ));
        }
        if !output.stdout.is_empty() {
            return Err("native Apply UCI batch returned unexpected output".to_string());
        }
        self.require_private_uci_clean()
    }

    fn restart_service(
        &mut self,
        request: &OperationRequest,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        self.run_instance_service_action(NativeApplyInstanceAction::Restart, request, lock)
    }

    fn verify_applied(&mut self, plan: &NativeApplyExecutionPlan) -> Result<(), String> {
        self.verify_candidate_bounded(plan)
    }

    fn discard_pending_uci_changes(&mut self) -> Result<(), String> {
        for package in ["cake-autorate", "sqm"] {
            let output = self.run_private_uci(&["-q", "revert", package], None)?;
            if !output.status.success() {
                return Err(format!(
                    "native Apply could not discard its private UCI changes for {package}: {}",
                    bounded_stderr(&output.stderr)
                ));
            }
        }
        self.require_private_uci_clean()?;
        self.require_clean_uci()
    }

    fn emergency_contain(
        &mut self,
        request: &OperationRequest,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        <Self as NativeApplyTransactionBackend>::discard_pending_uci_changes(self)?;
        self.run_instance_service_action(NativeApplyInstanceAction::Stop, request, lock)?;
        let cfg = Config::from_uci(&request.identity.instance)?;
        verify_direction_rate("download", &cfg.dl_if, None)?;
        verify_direction_rate("upload", &cfg.ul_if, None)?;
        if cfg.dl_if.starts_with("ifb") {
            let ingress = tc_output(&["filter", "show", "dev", &cfg.sqm_interface, "ingress"])?;
            crate::attest_download_redirect(&ingress, false, &cfg.sqm_interface, &cfg.dl_if)
                .map_err(|error| error.to_string())?;
        }
        Ok(())
    }

    fn verify_restored(
        &mut self,
        request: &OperationRequest,
        _record: &NativeApplyRecoveryRecord,
    ) -> Result<(), String> {
        self.verify_original_bounded(request)
    }

    fn verify_recovered_candidate(
        &mut self,
        request: &OperationRequest,
        record: &NativeApplyRecoveryRecord,
    ) -> Result<(), String> {
        if record.state != super::autotune_apply_runtime::NativeApplyRecoveryState::CommitAccepted {
            return Err("native Apply recovery candidate is not commit-accepted".to_string());
        }
        self.require_clean_uci()?;
        attest_openwrt_route_identity(request).map_err(|(code, message, _)| {
            format!("native Apply recovered route check failed ({code}): {message}")
        })?;
        let cfg = Config::from_uci(&request.identity.instance)?;
        let expected_section = request.managed_sqm_section.as_deref().ok_or_else(|| {
            "native Apply recovery request has no managed SQM section".to_string()
        })?;
        if cfg.sqm_interface != request.identity.target_interface
            || cfg.sqm_section != expected_section
        {
            return Err("native Apply recovered instance topology changed".to_string());
        }
        for (option, expected) in [
            ("_cake_autorate_managed", request.identity.instance.as_str()),
            ("interface", request.identity.target_interface.as_str()),
            ("enabled", if cfg.sqm_enabled { "1" } else { "0" }),
        ] {
            let query = format!("sqm.{expected_section}.{option}");
            let output = self.run_uci(&["-q", "get", &query], None)?;
            if !output.status.success() || parse_uci_scalar_output(&output.stdout)? != expected {
                return Err(format!(
                    "native Apply recovered SQM option {query} violates its owner contract"
                ));
            }
        }
        let expected_download = if cfg.download_shaping_enabled() {
            Some(exact_config_rate("download", cfg.base_dl_shaper_rate_kbps)?)
        } else {
            None
        };
        let expected_upload = if cfg.upload_shaping_enabled() {
            Some(exact_config_rate("upload", cfg.base_ul_shaper_rate_kbps)?)
        } else {
            None
        };
        verify_direction_rate("download", &cfg.dl_if, expected_download)?;
        verify_direction_rate("upload", &cfg.ul_if, expected_upload)?;
        if cfg.dl_if.starts_with("ifb") {
            let ingress = tc_output(&["filter", "show", "dev", &cfg.sqm_interface, "ingress"])?;
            crate::attest_download_redirect(
                &ingress,
                expected_download.is_some(),
                &cfg.sqm_interface,
                &cfg.dl_if,
            )
            .map_err(|error| error.to_string())?;
        }
        Ok(())
    }
}

impl NativeBootstrapApplyBackend for OpenWrtNativeApplyBackend {
    fn candidate_already_applied(
        &mut self,
        plan: &NativeBootstrapApplyPlan,
    ) -> Result<bool, String> {
        match self.verify_bootstrap_materialized_config(plan) {
            Ok(_) => {
                self.verify_bootstrap_running_candidate(
                    plan.request(),
                    Some(plan.source_apply().sqm_direction_mode.as_str()),
                    plan.mode(),
                    plan.absent_baseline(),
                )?;
                self.verify_bootstrap_materialized_config(plan)?;
                Ok(true)
            }
            Err(candidate_error) => match self
                .attest_bootstrap_absence(plan.request(), plan.absent_baseline())
            {
                Ok(()) => Ok(false),
                Err(absence_error) => Err(format!(
                    "native bootstrap target is neither the exact applied candidate nor the exact absent baseline: candidate={candidate_error}; absence={absence_error}"
                )),
            },
        }
    }

    fn attest_absent_before_mutation(
        &mut self,
        plan: &NativeBootstrapApplyPlan,
    ) -> Result<(), String> {
        self.attest_bootstrap_absence(plan.request(), plan.absent_baseline())
    }

    fn attest_candidate_before_restart(
        &mut self,
        plan: &NativeBootstrapApplyPlan,
    ) -> Result<(), String> {
        self.require_bootstrap_root()?;
        validate_bootstrap_request_baseline(plan.request(), plan.absent_baseline())?;
        self.require_clean_uci()?;
        attest_bootstrap_route(plan.request(), "candidate pre-restart preflight")?;
        self.verify_bootstrap_materialized_config(plan)?;
        if plan.mode() == NativeBootstrapApplyMode::DisabledInactive {
            require_selected_controller_absent(
                Path::new("/proc"),
                &plan.request().identity.instance,
            )?;
        }
        self.require_bootstrap_managed_slots_absent(plan.request())?;
        self.attest_bootstrap_kernel_bare(plan.request(), plan.absent_baseline())?;
        attest_bootstrap_route(plan.request(), "candidate pre-restart re-attestation")?;
        self.verify_bootstrap_materialized_config(plan)?;
        if plan.mode() == NativeBootstrapApplyMode::DisabledInactive {
            require_selected_controller_absent(
                Path::new("/proc"),
                &plan.request().identity.instance,
            )?;
        }
        self.require_bootstrap_managed_slots_absent(plan.request())?;
        self.require_clean_uci()?;
        attest_bootstrap_route(plan.request(), "candidate pre-restart final route fence")
    }

    fn restart_service(
        &mut self,
        request: &OperationRequest,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        self.run_bootstrap_instance_service_action(
            NativeApplyInstanceAction::Restart,
            request,
            lock,
        )
    }

    fn verify_applied(&mut self, plan: &NativeBootstrapApplyPlan) -> Result<(), String> {
        self.verify_bootstrap_materialized_config(plan)?;
        self.verify_bootstrap_running_candidate(
            plan.request(),
            Some(plan.source_apply().sqm_direction_mode.as_str()),
            plan.mode(),
            plan.absent_baseline(),
        )?;
        self.verify_bootstrap_materialized_config(plan)?;
        Ok(())
    }

    fn discard_pending_uci_changes(&mut self) -> Result<(), String> {
        <Self as NativeApplyTransactionBackend>::discard_pending_uci_changes(self)
    }

    fn quiesce_candidate_before_rollback(
        &mut self,
        request: &OperationRequest,
        record: &NativeBootstrapApplyRecoveryRecord,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        if record.state != NativeBootstrapApplyRecoveryState::RollbackRequired {
            return Err(
                "native bootstrap rollback quiesce lacks durable rollback authority".to_string(),
            );
        }
        let baseline = absent_baseline_from_record(request, record)?;
        match record.mode {
            NativeBootstrapApplyMode::ShapedRuntime => {
                self.quiesce_bootstrap_candidate(request, lock)?;
            }
            NativeBootstrapApplyMode::DisabledInactive => {
                self.require_bootstrap_root()?;
                self.require_clean_uci()?;
                attest_bootstrap_route(request, "disabled rollback quiesce preflight")?;
                self.verify_bootstrap_candidate_config(request, record.mode)?;
                require_selected_controller_absent(Path::new("/proc"), &request.identity.instance)?;
                self.require_bootstrap_managed_slots_absent(request)?;
            }
        }
        self.attest_bootstrap_kernel_bare(request, &baseline)
    }

    fn attest_rollforward_before_restart(
        &mut self,
        request: &OperationRequest,
        record: &NativeBootstrapApplyRecoveryRecord,
    ) -> Result<(), String> {
        if record.state != NativeBootstrapApplyRecoveryState::CommitAccepted {
            return Err("native bootstrap roll-forward lacks durable commit authority".to_string());
        }
        if record.mode != NativeBootstrapApplyMode::ShapedRuntime {
            return Err(
                "native disabled bootstrap candidate must not enter restart roll-forward"
                    .to_string(),
            );
        }
        let baseline = absent_baseline_from_record(request, record)?;
        self.require_bootstrap_root()?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "roll-forward pre-restart preflight")?;
        self.verify_bootstrap_candidate_config(request, record.mode)?;
        self.require_bootstrap_managed_slots_absent(request)?;
        self.attest_bootstrap_kernel_bare(request, &baseline)?;
        attest_bootstrap_route(request, "roll-forward pre-restart re-attestation")?;
        self.verify_bootstrap_candidate_config(request, record.mode)?;
        self.require_bootstrap_managed_slots_absent(request)?;
        self.require_clean_uci()?;
        attest_bootstrap_route(request, "roll-forward pre-restart final route fence")
    }

    fn verify_absent_restored(
        &mut self,
        request: &OperationRequest,
        baseline: &AbsentRuntimeBaseline,
    ) -> Result<(), String> {
        self.attest_bootstrap_absence(request, baseline)
    }

    fn verify_recovered_candidate(
        &mut self,
        request: &OperationRequest,
        record: &NativeBootstrapApplyRecoveryRecord,
    ) -> Result<(), String> {
        if record.state != NativeBootstrapApplyRecoveryState::CommitAccepted {
            return Err("native bootstrap recovered candidate is not commit-accepted".to_string());
        }
        let baseline = absent_baseline_from_record(request, record)?;
        self.verify_bootstrap_running_candidate(request, None, record.mode, &baseline)
    }

    fn emergency_contain(
        &mut self,
        request: &OperationRequest,
        mode: NativeBootstrapApplyMode,
        lock: &NativeApplyGlobalLock,
    ) -> Result<(), String> {
        <Self as NativeApplyTransactionBackend>::discard_pending_uci_changes(self)?;
        match mode {
            NativeBootstrapApplyMode::ShapedRuntime => {
                self.quiesce_bootstrap_candidate(request, lock)
            }
            NativeBootstrapApplyMode::DisabledInactive => {
                self.require_bootstrap_root()?;
                self.require_clean_uci()?;
                attest_bootstrap_route(request, "disabled containment preflight")?;
                require_selected_controller_absent(Path::new("/proc"), &request.identity.instance)?;
                self.require_bootstrap_managed_slots_absent(request)
            }
        }
    }
}

fn exact_config_rate(direction: &str, value: f64) -> Result<u64, String> {
    if !value.is_finite() || value < 1.0 || value > u64::MAX as f64 || value.fract() != 0.0 {
        return Err(format!(
            "native Apply recovered {direction} rate is not an exact integer"
        ));
    }
    Ok(value as u64)
}

fn validate_init_identifier(value: &str) -> Result<(), String> {
    if value.is_empty()
        || value.len() > 64
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    {
        return Err("native Apply init identifier is invalid".to_string());
    }
    Ok(())
}

fn validate_init_interface(value: &str) -> Result<(), String> {
    if value.is_empty()
        || value.len() > 64
        || !value.bytes().all(|byte| {
            byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'.' | b':' | b'@' | b'-')
        })
    {
        return Err("native Apply target interface is invalid".to_string());
    }
    Ok(())
}

fn verify_direction_rate(
    direction: &str,
    interface: &str,
    expected_kbps: Option<u64>,
) -> Result<(), String> {
    let interface_path = Path::new("/sys/class/net").join(interface);
    if !interface_path.exists() {
        return if expected_kbps.is_none() {
            Ok(())
        } else {
            Err(format!(
                "native Apply {direction} interface {interface} is missing"
            ))
        };
    }
    let output = tc_output(&["qdisc", "show", "dev", interface])?;
    match (expected_kbps, root_cake_qdisc_count(&output)) {
        (None, 0) => Ok(()),
        (None, _) => Err(format!(
            "native Apply disabled {direction} direction still has a root CAKE qdisc"
        )),
        (Some(_), count) if count != 1 => Err(format!(
            "native Apply {direction} direction has {count} root CAKE qdiscs"
        )),
        (Some(expected), 1) => {
            let (_, actual) = root_cake_qdisc(&output)?;
            if actual == expected {
                Ok(())
            } else {
                Err(format!(
                    "native Apply {direction} CAKE rate {actual} kbit/s differs from exact planned {expected} kbit/s"
                ))
            }
        }
        (Some(_), _) => unreachable!(),
    }
}

fn exact_uci_query(mutation: &NativeUciMutation) -> String {
    format!(
        "{}.{}.{}",
        mutation.package, mutation.section, mutation.option
    )
}

fn parse_uci_scalar_output(bytes: &[u8]) -> Result<&str, String> {
    let mut bytes = bytes;
    if let Some(stripped) = bytes.strip_suffix(b"\n") {
        bytes = stripped;
    }
    if bytes.is_empty() || bytes.contains(&b'\n') || bytes.contains(&b'\r') || bytes.contains(&0) {
        return Err("native Apply UCI scalar output is empty or malformed".to_string());
    }
    std::str::from_utf8(bytes)
        .map_err(|_| "native Apply UCI scalar output is not UTF-8".to_string())
}

fn bounded_stderr(bytes: &[u8]) -> String {
    std::str::from_utf8(bytes)
        .unwrap_or("non-UTF-8 error output")
        .trim()
        .chars()
        .take(512)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::operations::autotune_bootstrap_apply::tests::{
        fixture_plan, fixture_raw_fallback_plan,
    };

    fn test_root(name: &str) -> PathBuf {
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "cake-native-apply-openwrt-{}-{nonce}-{name}",
            std::process::id()
        ));
        let mut builder = DirBuilder::new();
        builder.mode(0o700).create(&path).unwrap();
        path
    }

    #[test]
    fn uci_scalar_output_is_exact_and_single_line() {
        assert_eq!(parse_uci_scalar_output(b"cake_wan\n").unwrap(), "cake_wan");
        assert_eq!(
            parse_uci_scalar_output(b"diffserv4 nat dual-dsthost\n").unwrap(),
            "diffserv4 nat dual-dsthost"
        );
        assert!(parse_uci_scalar_output(b"").is_err());
        assert!(parse_uci_scalar_output(b"one\ntwo\n").is_err());
        assert!(parse_uci_scalar_output(b"one\r\n").is_err());
    }

    #[test]
    fn default_paths_are_fixed_and_flash_recovery_is_not_in_tmp() {
        let paths = default_native_apply_paths();
        assert_eq!(
            paths.global_lock,
            Path::new("/tmp/cake-autorate-speedtest/runtime.guard")
        );
        assert_eq!(paths.cake_config, Path::new("/etc/config/cake-autorate"));
        assert_eq!(paths.sqm_config, Path::new("/etc/config/sqm"));
        assert!(paths.recovery_root.starts_with("/etc/"));
    }

    #[test]
    fn native_apply_uci_deltas_are_bound_to_one_private_tmpfs_savedir() {
        assert_eq!(PRIVATE_UCI_SAVEDIR, "/tmp/cake-autorate-native-apply-uci");
        assert_eq!(
            OpenWrtNativeApplyBackend::private_uci_arguments(&["-q", "batch"]),
            ["-t", PRIVATE_UCI_SAVEDIR, "-q", "batch"]
                .into_iter()
                .map(OsString::from)
                .collect::<Vec<_>>()
        );
    }

    fn bootstrap_config_fixture(request: &OperationRequest, direction_mode: &str) -> Config {
        let mut cfg = Config::defaults(request.identity.instance.clone());
        cfg.enabled = true;
        cfg.manage_sqm = true;
        cfg.sqm_enabled = true;
        cfg.sqm_direction_mode = direction_mode.to_string();
        cfg.sqm_section = request.managed_sqm_section.clone().unwrap();
        cfg.sqm_interface = request.route.l3_device.clone();
        cfg.ul_if = request.route.l3_device.clone();
        cfg.dl_if = format!("ifb4{}", request.route.l3_device);
        cfg.route_mode = request.route.mode.as_str().to_string();
        cfg.mwan3_member = request.route.mwan3_member.clone().unwrap_or_default();
        cfg.speedtest_backend = request.backend.clone();
        cfg
    }

    #[test]
    fn bootstrap_candidate_config_is_bound_to_managed_l3_not_the_requested_alias() {
        let plan = fixture_plan();
        let mut request = plan.request().clone();
        request.identity.target_interface = "requested-wan".to_string();
        let mut cfg = bootstrap_config_fixture(&request, "both");
        validate_bootstrap_candidate_config(
            &cfg,
            &request,
            NativeBootstrapApplyMode::ShapedRuntime,
        )
        .unwrap();

        cfg.sqm_interface = request.identity.target_interface.clone();
        assert!(validate_bootstrap_candidate_config(
            &cfg,
            &request,
            NativeBootstrapApplyMode::ShapedRuntime
        )
        .unwrap_err()
        .contains("immutable request topology"));
    }

    #[test]
    fn bootstrap_candidate_config_rejects_disabled_or_unshaped_runtime() {
        let plan = fixture_plan();
        let request = plan.request();
        let mut cfg = bootstrap_config_fixture(request, "both");
        cfg.enabled = false;
        assert!(validate_bootstrap_candidate_config(
            &cfg,
            request,
            NativeBootstrapApplyMode::ShapedRuntime
        )
        .is_err());

        let cfg = bootstrap_config_fixture(request, "off");
        assert!(validate_bootstrap_candidate_config(
            &cfg,
            request,
            NativeBootstrapApplyMode::ShapedRuntime
        )
        .is_err());

        let mut cfg = bootstrap_config_fixture(request, "both");
        cfg.speedtest_backend = "auto".to_string();
        assert!(validate_bootstrap_candidate_config(
            &cfg,
            request,
            NativeBootstrapApplyMode::ShapedRuntime
        )
        .is_err());
    }

    #[test]
    fn disabled_bootstrap_candidate_requires_exact_inactive_shape() {
        let plan = fixture_raw_fallback_plan();
        let request = plan.request();
        let mut cfg = bootstrap_config_fixture(request, "off");
        cfg.enabled = false;
        cfg.sqm_enabled = false;
        validate_bootstrap_candidate_config(
            &cfg,
            request,
            NativeBootstrapApplyMode::DisabledInactive,
        )
        .unwrap();

        for mutation in ["enabled", "sqm_enabled", "direction"] {
            let mut changed = cfg.clone();
            match mutation {
                "enabled" => changed.enabled = true,
                "sqm_enabled" => changed.sqm_enabled = true,
                "direction" => changed.sqm_direction_mode = "download_only".to_string(),
                _ => unreachable!(),
            }
            assert!(validate_bootstrap_candidate_config(
                &changed,
                request,
                NativeBootstrapApplyMode::DisabledInactive
            )
            .unwrap_err()
            .contains("strictly inactive"));
        }
    }

    #[test]
    fn disabled_controller_absence_uses_exact_bounded_cmdline_identity() {
        let root = test_root("proc-controller");
        for (pid, cmdline) in [
            (
                "101",
                b"/usr/sbin/cake-autorated\0--instance\0other\0".as_slice(),
            ),
            (
                "102",
                b"/usr/sbin/cake-autorated-helper\0--instance\0wan_sqm\0".as_slice(),
            ),
            (
                "103",
                b"/usr/sbin/cake-autorated\0--instance\0wan_sqm\0--extra\0".as_slice(),
            ),
        ] {
            let process = root.join(pid);
            fs::create_dir(&process).unwrap();
            fs::write(process.join("cmdline"), cmdline).unwrap();
        }
        require_selected_controller_absent(&root, "wan_sqm").unwrap();

        let unrelated = root.join("105");
        fs::create_dir(&unrelated).unwrap();
        let mut unrelated_cmdline = b"/usr/bin/apcontroller\0".to_vec();
        unrelated_cmdline.extend(std::iter::repeat_n(b'x', PROC_CMDLINE_LIMIT as usize + 32));
        unrelated_cmdline.push(0);
        fs::write(unrelated.join("cmdline"), unrelated_cmdline).unwrap();
        require_selected_controller_absent(&root, "wan_sqm").unwrap();

        let oversized = root.join("106");
        fs::create_dir(&oversized).unwrap();
        let mut oversized_cmdline = b"/usr/sbin/cake-autorated\0--instance\0wan_sqm\0".to_vec();
        oversized_cmdline.extend(std::iter::repeat_n(b'y', PROC_CMDLINE_LIMIT as usize + 32));
        fs::write(oversized.join("cmdline"), oversized_cmdline).unwrap();
        assert!(require_selected_controller_absent(&root, "wan_sqm")
            .unwrap_err()
            .contains("exceeds its safety bound"));
        fs::remove_dir_all(oversized).unwrap();

        let selected = root.join("104");
        fs::create_dir(&selected).unwrap();
        fs::write(
            selected.join("cmdline"),
            b"/usr/sbin/cake-autorated\0--instance\0wan_sqm\0",
        )
        .unwrap();
        assert!(require_selected_controller_absent(&root, "wan_sqm")
            .unwrap_err()
            .contains("live controller"));
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn bootstrap_materializer_verifies_both_exact_typed_target_sections() {
        let plan = fixture_plan();
        let materialization =
            NativeUciMaterializationPlan::from_managed_config(plan.managed_config()).unwrap();
        let candidate = materialization
            .deterministic_candidate_pair(
                b"config globals 'globals'\n\toption enabled '0'\n",
                b"config queue 'existing'\n\toption enabled '0'\n",
            )
            .unwrap();
        materialization
            .verify_exact_config_files(candidate.cake(), candidate.sqm())
            .unwrap();
        assert!(materialization
            .verify_exact_config_files(candidate.cake(), b"config queue 'existing'\n")
            .is_err());

        let mut tampered_cake = candidate.cake().to_vec();
        tampered_cake.extend_from_slice(b"\toption enabled '0'\n");
        assert!(materialization
            .verify_exact_config_files(&tampered_cake, candidate.sqm())
            .is_err());
    }

    #[test]
    fn bootstrap_managed_slots_accept_only_kernel_defaults_and_empty_ingress() {
        validate_bootstrap_managed_slot_output(
            "eth0",
            concat!(
                "qdisc mq 0: root\n",
                "qdisc fq_codel 0: parent :1 limit 10240p\n"
            ),
            "",
        )
        .unwrap();
        validate_bootstrap_managed_slot_output("pppoe-wan", "qdisc noqueue 0: root\n", "\n")
            .unwrap();

        assert!(validate_bootstrap_managed_slot_output(
            "eth0",
            "qdisc cake 8010: root bandwidth 100Mbit\n",
            ""
        )
        .unwrap_err()
        .contains("foreign root qdisc"));
        assert!(validate_bootstrap_managed_slot_output(
            "eth0",
            "qdisc ingress ffff: parent ffff:fff1\n",
            ""
        )
        .unwrap_err()
        .contains("ingress/clsact"));
        assert!(validate_bootstrap_managed_slot_output(
            "eth0",
            "qdisc noqueue 0: root\n",
            "filter parent ffff: protocol all pref 10 u32\n"
        )
        .unwrap_err()
        .contains("ingress filter ownership"));
    }

    #[test]
    fn bootstrap_backend_has_no_timer_driven_retry_or_false_fallback() {
        let source = include_str!("autotune_apply_openwrt.rs");
        let bootstrap = source
            .split_once("impl NativeBootstrapApplyBackend for OpenWrtNativeApplyBackend")
            .unwrap()
            .1;
        let bootstrap = bootstrap.split_once("fn exact_config_rate").unwrap().0;
        assert!(!bootstrap.contains("thread::sleep"));
        assert!(!bootstrap.contains("verify_candidate_once(plan).is_ok()"));
        assert!(
            bootstrap.contains("neither the exact applied candidate nor the exact absent baseline")
        );
    }
}
