#!/bin/sh

printf '%s %s\n' "$1" "$2" >> "$CAKE_TEST_ROOT/actions"
[ -n "${UCI_CONFIG_DIR:-}" ] || exit 94
[ -f "$UCI_CONFIG_DIR/sqm" ] && [ ! -L "$UCI_CONFIG_DIR/sqm" ] || exit 95
printf '%s\n' "$UCI_CONFIG_DIR" >> "$CAKE_TEST_ROOT/uci-config-dirs"
if [ "$1" = start ]; then
	[ "${CAKE_TEST_SQM_START_FAIL:-0}" != 1 ] || exit 1
	rm -f "$CAKE_TEST_ROOT/tc-mode"
	mkdir -p "$CAKE_AUTORATE_SYS_CLASS_NET/ifb4eth0/statistics" \
		"$CAKE_AUTORATE_SYS_CLASS_NET/eth0/statistics"
	: > "$CAKE_AUTORATE_SYS_CLASS_NET/ifb4eth0/statistics/tx_bytes"
	: > "$CAKE_AUTORATE_SYS_CLASS_NET/eth0/statistics/rx_bytes"
	: > "$CAKE_AUTORATE_SYS_CLASS_NET/eth0/statistics/tx_bytes"
	{
		printf 'IFACE="eth0"\n'
		printf 'QDISC="cake"\n'
		printf 'SCRIPT="piece_of_cake.qos"\n'
		printf 'UPLINK="20000"\n'
		printf 'DOWNLINK="100000"\n'
		printf 'LINKLAYER="none"\n'
		printf 'LLAM="default"\n'
		printf 'OVERHEAD="0"\n'
		printf 'STAB_MPU="0"\n'
		printf 'USE_MQ="0"\n'
		printf 'INGRESS_CAKE_OPTS="diffserv3 nat besteffort wash"\n'
		printf 'EGRESS_CAKE_OPTS="diffserv3 nat besteffort"\n'
		printf 'IQDISC_OPTS=""\n'
		printf 'EQDISC_OPTS=""\n'
		printf 'ZERO_DSCP_INGRESS="0"\n'
		printf 'IGNORE_DSCP_INGRESS="0"\n'
	} > "$CAKE_AUTORATE_SQM_STATE_DIR/eth0.state"
	: > "$CAKE_TEST_ROOT/healthy"
fi
